### ISSUE TITLE
poetry

### ISSUE THREAD

**Issue by killmealready** [DrShahinstein/whatsapp-cli#2]
its not detcting poetry. how do i solve that?

**Comment by DrShahinstein** [comment]
What do you mean by not detecting? You'd like to clarify with screenshots or maybe test cases.

**Comment by killmealready** [comment]
nevermind. solved it already. im new to this. doing this stuff alone is pure torture but the moment it works i feel like a dopamine rush. anyways, i got another issue. ur code opens opera, logs in, but it only pastes the message and doesnt send. how do i solve that? i confirmed and everything is installed correctly. poetry, build,...
Also, sorry for the delay but this weekend i didnt even opened github.
And one final question, is it possible to change the browser it is going to? currently it's going to opera but i'm going to try to put it on brave.

**Comment by DrShahinstein** [comment]
After it pastes the message, wait for 10 seconds. Then, it should send the message. 
```
def send_message(schedule):
    url = 'https://web.whatsapp.com/send?phone=' + \
        schedule["receiver"] + '&text=' + schedule["message"]
    webbrowser.open(url)
    timer = threading.Timer(10, lambda: pyautogui.press("enter"))
    timer.run()
    remove_schedule(schedule["name"])
```
Here, as you can see, `webbrowser` module opens Whatsapp Web and then, there's the timer going to press enter after 10 seconds. 

As for the browser issue, again, as you can see, the code opens the browser using `webbrowser` module's `.open()` method which means it's going to open your default browser on your pc. You'd like to change your default browser to open Brave or maybe find another code opening browsers.
